#
#Dependencies
markdown:            redcarpet
highlighter:         pygments


# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Reage
author:              Reage
tagline:             ''
description:         ''
url:                 http://www.ireage.com
baseurl:             /
paginate:            5
github:				 https://github.com/rentiansheng
rss:				 /atom.xml
# Custom vars
version:             1.5.0
