#
#Dependencies
markdown:            kramdown
highlighter:         Rouge


# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           paginate
relative_permalinks: false

# Gems
gems: [jekyll-paginate]


# Setup
title:               'Reage blog'
author:              Reage
tagline:             ''
description:         ''
url:                 http://www.ireage.com
baseurl:             /
paginate:            5
paginate_path:       "page:num"
github:				 https://github.com/rentiansheng
rss:				 /atom.xml
# Custom vars
version:             1.5.0
